# lit-bit-core/.cargo/config.toml
# This file is intentionally kept minimal.
# Target-specific rustflags and runner configurations that apply to the entire
# workspace (including examples) have been moved to the workspace root:
# /Users/joseflores/Development/lit-bit/.cargo/config.toml
#
# This ensures that Cargo correctly picks up these settings when building
# examples or any crate from the workspace root, as per Cargo's configuration
# resolution rules documented at:
# https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure
#
# If this crate ('lit-bit-core') had build-time configurations that are *truly*
# specific only to its direct compilation and not meant for general target setup
# (e.g., a crate-specific `--cfg` flag not related to the target architecture),
# they could be placed here.

[build]
# Example of a truly crate-specific build setting (if ever needed):
# rustflags = ["--cfg=lit_bit_core_specific_feature"]

# Previously defined target-specific sections for riscv32imac-unknown-none-elf
# and thumbv7m-none-eabi have been moved to the workspace root config.
